bizanalytic/logiflex/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "logiflex"


newsletter_patterns = [
    path("create/", views.NewsletterCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.NewsletterEditView.as_view(), name="edit"),
    path("list/", views.NewsletterListView.as_view(), name="list"),
    path("subscrib/", views.NewsletterSubscriptionCreateView.as_view(), name="subscrib"),
    path("editsubscrib/<int:pk>/", views.NewsletterSubscriptionEditView.as_view(), name="editsubscrib"),
    path("subscribtionlist/", views.NewsletterSubscriptionListView.as_view(), name="subscribtionlist"),
]

report_patterns = [
    path("create/", views.SampleReportCreateView.as_view(), name="create"),

]

stripe_patterns = [
    path('', views.Payment_PageView.as_view(), name='payment_page'),
    path('create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('stripe_webhook/', views.WebhookView.as_view(), name='stripe_webhook'),
    path('success/', views.Payment_SuccessView.as_view(), name='success'),
    path('cancel/', views.Payment_FailView.as_view(), name='cancel'),
]

urlpatterns = [

    path("", views.IndexView.as_view(), name="index"),
    path("book-call/", views.RequestCallView.as_view(), name="book-call"),
    path("bookcall/", views.BookACallView.as_view(), name="bookcall"),
    path(
        "newsletters/",
        include((newsletter_patterns, "bizanalytic.logiflex"), namespace="newsletters"),
    ),
    path(
        "reports/",
        include((report_patterns, "bizanalytic.logiflex"), namespace="reports"),
    ),
    path(
        "securepay/",
        include((stripe_patterns, "bizanalytic.logiflex"), namespace="securepay"),
    ),

]

bizanalytic/profiles/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "profiles"

enterprise_patterns = [
    path("create/", views.EnterpriseCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.EnterpriseEditView.as_view(), name="edit"),
]


urlpatterns = [
    path("language/<int:pk>/", views.LanguageUpdateView.as_view(), name="language"),
    path("userinfo/<int:pk>/", views.ProfilesUpdateView.as_view(), name="userinfo"),
    path("activate/<int:pk>/", views.ProfileActivateView.as_view(), name="activate"),
    path("", views.ProfileDetailView.as_view(), name="profile"),
    path("edit/", views.ProfileView.as_view(), name="editprofile"),
    path("dispatch-login/", views.DispatchLoginView.as_view(), name="dispatch_login"),
    path("member/", views.RegularUpdateView.as_view(), name="regular"),
    path("admin/", views.AdminUpdateView.as_view(), name="admin"),
    # path("<int:pk>/add-review", views.ReviewCreateView.as_view(), name="review_create"),
    path("<int:pk>/contact-request/", views.ContactRequestView.as_view(), name="contact_request"),
    path("detail/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("403/", views.ForbiddenView.as_view(), name="403"),
    path("conditions/", views.ConditionsView.as_view(), name="conditions"),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    # path("Freecourses/", views.FreecoursesView.as_view(), name="freecourses"),
    # path("uploadusers/", views.user_upload, name="userupload"),
    # path("uploadposts/", views.posts_upload, name="uploadposts"),
    # path("createusers/", views.UsersCreate.as_view(), name="createusers"),
    # url('^createnewusers$', views.NewUserCreateView.as_view(), name="createnewusers"),
    # path("tenants/", include((tenants_patterns, "syndicma.profiles"), namespace="tenants")),
    path(
        "enterprise/",
        include((enterprise_patterns, "bizanalytic.profiles"), namespace="enterprise"),
    ),
    # path(
    #     "activeyear/",
    #     include((activeyear_patterns, "syndicma.profiles"), namespace="activeyears"),
    # ),
]

bizanalytic/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog
# from api.verify.views import FileUpdateView, DocumentScanView, PictureVerifyView, FileUpdatetestView, \
#     DocumentVerifiedView, HeadshotVerifiedView

# from coelinks.profiles.views import ProfileView
# from rest_framework.routers import DefaultRouter
# from api.verify.views import FileUpdateView, DocumentScanView
# from api.chatbot.views import ChatGenerateView
#
# router = DefaultRouter()
#
# router.register(r"verify/", FileUpdateView, basename="verify")
# router.register(r"chat/", ChatGenerateView, basename="chat")

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path("logiflex/", include("bizanalytic.logiflex.urls", namespace="logiflex")),
    path("", RedirectView.as_view(pattern_name="logiflex:index")),
    path("accounts/", include("allauth.urls")),
    # path("accounts/profile/", ProfileView.as_view()),
    # path("apis/chat/", include("api.chat.urls", namespace="chat")),
    path("profiles/", include("bizanalytic.profiles.urls", namespace="profiles")),
    # path("coeanalytics/", include("coelinks.coeanalytics.urls", namespace="coeanalytics")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("i18n/", include("django.conf.urls.i18n")),




    # path('api/verify/', FileUpdateView.as_view(), name='verify'),
    # path('api/testverify/', FileUpdatetestView.as_view(), name='testverify'),
    # path('api/scan/', DocumentScanView.as_view(), name='scan'),
    # path('api/endverify/', DocumentVerifiedView.as_view(), name='endverify'),
    # path('api/headshotverified/', HeadshotVerifiedView.as_view(), name='headshotverified'),
    # path('api/checkimage/', PictureVerifyView.as_view(), name='checkimage'),
    # path('api/chat/', include('api.chatbot.urls', namespace='chat')),
    # path("api/ocr/", include('api.ocrserver.urls', namespace='ocr')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bizanalytic/logiflex/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from . import models


class NewsLetter_logiflexForm(forms.ModelForm):
    class Meta:
        model = models.NewsLetter_logiflex
        fields = ["title", "body"]
        labels = {
            "title": _("Title"),
            "body": _("Body")
        }


class NewsLetter_logiflex_subscriptionForm(forms.ModelForm):
    class Meta:
        model = models.NewsLetter_logiflex_subscription
        fields = ["email", "company", "area"]
        labels = {
            "email": _("Email"),
            "company": _("Company Name"),
            "area": _("Area")
        }

bizanalytic/logiflex/views.py
from django.shortcuts import render
from django.views.generic import (
    UpdateView,
    RedirectView,
    CreateView,
    View,
    TemplateView,
    DetailView,
    ListView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.http import JsonResponse, HttpResponse
from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.views.decorators.csrf import csrf_exempt

# Third party libraries
import stripe

from . import models, forms
from bizanalytic.profiles.mixins import JsonFormMixin
from bizanalytic.profiles.models import User
from .utils.mail import sendemail
# Create your views here.

# Initiate variables
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe_price_id = settings.STRIPE_PRICE_ID
stripe_publishable = settings.STRIPE_PUBLISHABLE_KEY
stripe_webhook = settings.STRIPE_WEBHOOK_SECRET

class IndexView(TemplateView):
    template_name = "../templates/logiflex/home.html"


class NewsletterCreateView(UserPassesTestMixin, CreateView):
    model = models.NewsLetter_logiflex
    form_class = forms.NewsLetter_logiflexForm
    template_name = "logiflex/newsletter_logiflex_create.html"
    success_url = reverse_lazy("logiflex:newsletters:list")

    def test_func(self):
        return self.request.user.is_staff


class NewsletterEditView(UserPassesTestMixin, UpdateView):
    model = models.NewsLetter_logiflex
    form_class = forms.NewsLetter_logiflexForm
    template_name = "logiflex/newsletter_logiflex_create.html"
    success_url = reverse_lazy("logiflex:newsletters:list")

    def test_func(self):
        return self.request.user.is_staff


class NewsletterListView(UserPassesTestMixin, ListView):
    model = models.NewsLetter_logiflex
    template_name = "logiflex/newsletter_logiflex_list.html"

    def test_func(self):
        return self.request.user.is_staff


class NewsletterSubscriptionCreateView(CreateView, JsonFormMixin):
    def post(self, request, *args, **kwargs):

        # load AJAX data from the template
        cp_name = request.POST.get("cp_name")
        if cp_name:
            cp_name = cp_name.lower()
        else:
            cp_name = "none"
        email_nl = request.POST.get("em_nl").lower()
        tp_area = int(request.POST.get("tp_area"))

        # Search the database for the email
        subs = models.NewsLetter_logiflex_subscription.objects.filter(email=email_nl).first()

        # Check if data exists or not in the database
        message = ""
        if subs:
            company = subs.company.lower()
            if company == "none":
                if cp_name == "none":
                    message = _("Thank you for your request. This email is already registered with us")
                else:
                    message = _("Thank you for your request. You have been registered Successfully")
                    area = ""
                    if tp_area == 1:
                        area = "lo"
                    elif tp_area == 2:
                        area = "ki"
                    subs.company = cp_name
                    subs.area = area
                    subs.save()
            else:
                if cp_name == "none" or not cp_name == company:
                    message = _("Thank you for your request. This email is already registered under different company name")
                elif cp_name == company:
                    message = _("Thank you for your request. This email is already registered with us")
        else:
            message = _("Thank you for your request. You have been registered Successfully")
            area = ""
            if tp_area == 1:
                area = "lo"
            elif tp_area == 2:
                area = "ki"
            subscription = models.NewsLetter_logiflex_subscription(email=email_nl, company=cp_name, area=area)
            subscription.save()

        data = {"submessage": message}

        return JsonResponse(data)


class NewsletterSubscriptionEditView(UserPassesTestMixin, UpdateView):
    model = models.NewsLetter_logiflex_subscription
    form_class = forms.NewsLetter_logiflex_subscriptionForm
    template_name = "logiflex/newslettersubscrib_logiflex_create.html"
    success_url = reverse_lazy("logiflex:newsletters:list")

    def test_func(self):
        return self.request.user.is_staff


class NewsletterSubscriptionListView(UserPassesTestMixin, ListView):
    model = models.NewsLetter_logiflex_subscription
    template_name = "logiflex/newslettersubscription_logiflex_list.html"

    def test_func(self):
        return self.request.user.is_staff


class SampleReportCreateView(CreateView, JsonFormMixin):
    def post(self, request, *args, **kwargs):

        # load AJAX data from the template
        client_nm = request.POST.get("client_nm")
        cp_name = request.POST.get("cp_nm")
        email_name = request.POST.get("email_nm")
        email_name = email_name.lower()
        route_file = request.FILES["route_file"]

        # Save client and result data
        user = User.objects.filter(email=email_name).first()
        if user:
            client = models.LogiFlexClient.objects.filter(user=user).first()
            if client:
                report = models.LogiflexReport(client=client, routefile=route_file)
                report.save()
            else:
                obj, created = models.LogiFlexClient.objects.update_or_create(email=email_name,
                                                                              defaults={'company': cp_name,
                                                                                        'user': user,
                                                                                        'contact_name': client_nm})
                report = models.LogiflexReport(client=obj, routefile=route_file)
                report.save()
        else:
            client = models.LogiFlexClient.objects.filter(email=email_name).first()
            if client:
                report = models.LogiflexReport(client=client, routefile=route_file)
                report.save()
            else:
                obj, created = models.LogiFlexClient.objects.update_or_create(email=email_name,
                                                                              defaults={'company': cp_name,
                                                                                        'contact_name': client_nm})
                report = models.LogiflexReport(client=obj, routefile=route_file)
                report.save()
        print("route file", report.routefile)
        # Create a report
        email_info = {
            'subject': "🚀 Your Monthly Logistics Performance Report is Here",
            'to_email': [email_name,],
            'company': cp_name,
            'client_name': client_nm,
            'shipments': "187",
            'avgdelivery': "2.3",
            'percent_change': 12,
            'ontimedelivery': 94,
            'delayreasons': "Top 3 Reasons",
            'suggested': "Route X, Carrier Y",
            'logiflex_contact': "Adam Akad",
            'phone': "+1 (832) 430-2434",
            'cc': [""],
            'bcc': [""],
            'attachments': report.routefile
        }
        sendemail(email_info)
        message = "Report Created Succssefully"

        data = {"submessage": message}

        return JsonResponse(data)


class RequestCallView(TemplateView):
    template_name = "logiflex/call.html"


class BookACallView(CreateView, JsonFormMixin):
    def post(self, request, *args, **kwargs):
        message = ""
        cp_name = request.POST.get("cp_nm")
        client_name = request.POST.get("client_nm")
        email_name = request.POST.get("email_nm")
        email_name = email_name.lower()
        phone_nb = request.POST.get("phone_nb")

        client = models.LogiFlexClient.objects.filter(email=email_name).first()
        if client:
            if not client.contact_name:
                client.contact_name = client_name
            if not client.company:
                client.company = cp_name
            if not client.phone or not client.phone == phone_nb:
                client.phone = phone_nb
            client.save()
            call = models.RequestedCall(client=client)
            call.save()
            message = "Thank you for choosing BizAnalytic + LogiFlex to power your freight analytics. " \
                      "You will be contacted As Quick As Possible"

        data = {"submessage": message}

        return JsonResponse(data)


def create_checkout_session(request):

    if request.method == 'POST':
        try:
            # Validate input parameters
            # price_id = request.POST.get('price_id')
            # if not price_id:
            #     raise ValueError("Missing price ID")

            # Create checkout session
            print("Start Stripe Session")
            print(settings.FRONTEND_SUCCESS_URL)
            session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=[{
                    'price': stripe_price_id,
                    'quantity': 1,
                }],
                mode='payment',
                success_url=settings.FRONTEND_SUCCESS_URL + '?session_id={CHECKOUT_SESSION_ID}',
                cancel_url=settings.FRONTEND_CANCEL_URL,
                # customer_email=request.user.email if request.user.is_authenticated else None,
                # metadata={
                #     'user_id': request.user.id if request.user.is_authenticated else 'anonymous',
                #     'order_id': '141'
                # }
            )
            print("Session ID:", session.id)
            data = {"sessionId": session.id}
            return JsonResponse(data)

        except (ValueError, stripe.error.StripeError) as e:

bizanalytic/templates/base.html
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
	<meta charset="utf-8">
    {% block head_title %}
        <title>Idme.ma</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content={% trans "AI-Powered Analytics for Feight, Transport, logistics and small to medium businesses (SMB)" %}>
        <meta name="author" content="">
	{% endblock %}

    {% block css %}
	<!-- ================== BEGIN core-css ================== -->
        <link href={% static "assets/css/vendor.min.css" %} rel="stylesheet">
        <link href={% static "assets/css/app.min.css" %} rel="stylesheet">

	<!-- ================== END core-css ================== -->
	{% endblock css %}

</head>
<body>
	<!-- BEGIN #app -->
	<div id="app" class="app app-sidebar-collapsed">
		<!-- BEGIN #header -->
        {% block header %}
		<div id="header" class="app-header">
			<!-- BEGIN desktop-toggler -->
			<div class="desktop-toggler">
				<button type="button" class="menu-toggler" data-toggle-class="app-sidebar-collapsed" data-dismiss-class="app-sidebar-toggled" data-toggle-target=".app">
					<span class="bar"></span>
					<span class="bar"></span>
					<span class="bar"></span>
				</button>
			</div>
			<!-- BEGIN desktop-toggler -->
			
			<!-- BEGIN mobile-toggler -->
			<div class="mobile-toggler">
				<button type="button" class="menu-toggler" data-toggle-class="app-sidebar-mobile-toggled" data-toggle-target=".app">
					<span class="bar"></span>
					<span class="bar"></span>
					<span class="bar"></span>
				</button>
			</div>
			<!-- END mobile-toggler -->
			
			<!-- BEGIN brand -->
			<div class="brand">
				<a href="https://bizanalytic.com/" class="brand-logo">
                    <img src="{% static "assets/logo/logo1-1.png" %}" width="100px">
{#					<span class="brand-img">#}
{#						<span class="brand-img-text text-theme">I</span>#}
{#					</span>#}
{#					<span class="brand-text">ID-ME</span>#}
				</a>
			</div>
			<!-- END brand -->
			
			<!-- BEGIN menu -->
			<div class="menu">
				<div class="menu-item dropdown">
					<a href="#" data-toggle-class="app-header-menu-search-toggled" data-toggle-target=".app" class="menu-link">
						<div class="menu-icon"><i class="bi bi-search nav-icon"></i></div>
					</a>
				</div>
				<div class="menu-item dropdown dropdown-mobile-full">
					<a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
						<div class="menu-icon"><i class="bi bi-grid-3x3-gap nav-icon"></i></div>
					</a>
					<div class="dropdown-menu fade dropdown-menu-end w-300px text-center p-0 mt-1">
						<div class="row row-grid gx-0">
							<div class="col-4">
								<a href="#" class="dropdown-item text-decoration-none p-3 bg-none">
									<div class="position-relative">
										<i class="bi bi-circle-fill position-absolute text-theme top-0 mt-n2 me-n2 fs-6px d-block text-center w-100"></i>
										<i class="bi bi-envelope h2 opacity-5 d-block my-1"></i>
									</div>
									<div class="fw-500 fs-10px text-inverse">{% trans "INBOX" %}</div>
								</a>
							</div>
							<div class="col-4">
								<a href="#" target="_blank" class="dropdown-item text-decoration-none p-3 bg-none">
									<div><i class="bi bi-hdd-network h2 opacity-5 d-block my-1"></i></div>
									<div class="fw-500 fs-10px text-inverse">{% trans "POS SYSTEM" %}</div>
								</a>
							</div>
							<div class="col-4">
								<a href="#" class="dropdown-item text-decoration-none p-3 bg-none">
									<div><i class="bi bi-calendar4 h2 opacity-5 d-block my-1"></i></div>
									<div class="fw-500 fs-10px text-inverse">{% trans "CALENDAR" %}</div>
								</a>
							</div>
						</div>
						<div class="row row-grid gx-0">
							<div class="col-4">
								<a href="#" class="dropdown-item text-decoration-none p-3 bg-none">
									<div><i class="bi bi-terminal h2 opacity-5 d-block my-1"></i></div>
									<div class="fw-500 fs-10px text-inverse">{% trans "HELPER" %}</div>
								</a>
							</div>
							<div class="col-4">
								<a href="#" class="dropdown-item text-decoration-none p-3 bg-none">
									<div class="position-relative">
										<i class="bi bi-circle-fill position-absolute text-theme top-0 mt-n2 me-n2 fs-6px d-block text-center w-100"></i>
										<i class="bi bi-sliders h2 opacity-5 d-block my-1"></i>
									</div>
									<div class="fw-500 fs-10px text-inverse">{% trans "SETTINGS" %}</div>
								</a>
							</div>
							<div class="col-4">
								<a href="#" class="dropdown-item text-decoration-none p-3 bg-none">
									<div><i class="bi bi-collection-play h2 opacity-5 d-block my-1"></i></div>
									<div class="fw-500 fs-10px text-inverse">{% trans "WIDGETS" %}</div>
								</a>
							</div>
						</div>
					</div>
				</div>
				<div class="menu-item dropdown dropdown-mobile-full">
					<a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
						<div class="menu-icon"><i class="bi bi-bell nav-icon"></i></div>
						<div class="menu-badge bg-theme"></div>
					</a>
					<div class="dropdown-menu dropdown-menu-end mt-1 w-300px fs-11px pt-1">
						<h6 class="dropdown-header fs-10px mb-1">{% trans "NOTIFICATIONS" %}</h6>
						<div class="d-flex align-items-center py-10px dropdown-item text-wrap fs-6 bg-inverse bg-opacity-15 text-inverse text-opacity-50 h-100px">
							{% trans "No record found" %}
						</div>
						<hr class="my-0">
						<div class="py-10px mb-n2 text-center">
							<a href="#" class="text-decoration-none fw-bold">{% trans "SEE ALL" %}</a>
						</div>
					</div>
				</div>
				<div class="menu-item dropdown dropdown-mobile-full">
                    {% if user.is_authenticated %}
                        <a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
                            <div class="menu-img online">
                                {% if user.picture %}
							        <img src="{{ user.picture.url }}" alt="Profile" height="60">
                                {% else %}
                                    <div class="d-flex align-items-center justify-content-center w-100 h-100 bg-inverse bg-opacity-25 text-inverse text-opacity-50 rounded-circle overflow-hidden">
                                            <i class="bi bi-person-fill fs-32px mb-n3"></i>
                                    </div>
                                {% endif %}
						    </div>


                                <div class="menu-text d-sm-block d-none w-170px">{{ user.first_name }}</div>


                        </a>
                    {% else %}
                        <a href="#" data-bs-display="static" class="menu-link">
                            <div class="menu-img online">
                                <div class="d-flex align-items-center justify-content-center w-100 h-100 bg-inverse bg-opacity-25 text-inverse text-opacity-50 rounded-circle overflow-hidden">
                                    <i class="bi bi-person-fill fs-32px mb-n3"></i>
                                </div>
                            </div>

                                <div class="menu-text d-sm-block d-none w-170px">{% trans "User Name" %}</div>

                         </a>

                    {% endif %}
					<div class="dropdown-menu dropdown-menu-end me-lg-3 fs-11px mt-1">
						<a class="dropdown-item d-flex align-items-center" href="{% url 'profiles:profile' %}">{% trans "PROFILE" %} <i class="bi bi-person-circle ms-auto text-theme fs-16px my-n1"></i></a>
						<a class="dropdown-item d-flex align-items-center" href="#">{% trans "INBOX" %} <i class="bi bi-envelope ms-auto text-theme fs-16px my-n1"></i></a>
						<a class="dropdown-item d-flex align-items-center" href="#">{% trans "CALENDAR" %} <i class="bi bi-calendar ms-auto text-theme fs-16px my-n1"></i></a>
						<a class="dropdown-item d-flex align-items-center" href="#">{% trans "SETTINGS" %} <i class="bi bi-gear ms-auto text-theme fs-16px my-n1"></i></a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item d-flex align-items-center" href="{% url 'account_logout' %}">{% trans "LOGOUT" %} <i class="bi bi-toggle-off ms-auto text-theme fs-16px my-n1"></i></a>
					</div>
				</div>
			</div>
			<!-- END menu -->
			
			<!-- BEGIN menu-search -->
			<form class="menu-search" method="POST" name="header_search_form">
				<div class="menu-search-container">
					<div class="menu-search-icon"><i class="bi bi-search"></i></div>
					<div class="menu-search-input">
						<input type="text" class="form-control form-control-lg" placeholder="{% trans "Search menu" %}...">
					</div>
					<div class="menu-search-icon">
						<a href="#" data-toggle-class="app-header-menu-search-toggled" data-toggle-target=".app"><i class="bi bi-x-lg"></i></a>
					</div>
				</div>
			</form>
			<!-- END menu-search -->
		</div>
    {% endblock header %}
		<!-- END #header -->

		<!-- BEGIN #sidebar -->
    {% block sidebar %}
		<div id="sidebar" class="app-sidebar">
			<!-- BEGIN scrollbar -->
			<div class="app-sidebar-content" data-scrollbar="true" data-height="100%">
				<!-- BEGIN menu -->
				<div class="menu">
					<div class="menu-header">{% trans "Navigation" %}</div>
					<div class="menu-item active">
						<a href="" class="menu-link">
							<span class="menu-icon"><i class="bi bi-house-door"></i></span>
							<span class="menu-text">{% trans "Home" %}</span>
						</a>
					</div>
				</div>
				<!-- END menu -->
			</div>
			<!-- END scrollbar -->
		</div>
    {% endblock sidebar %}
		<!-- END #sidebar -->
			
		<!-- BEGIN mobile-sidebar-backdrop -->
		<button class="app-sidebar-mobile-backdrop" data-toggle-target=".app" data-toggle-class="app-sidebar-mobile-toggled"></button>
		<!-- END mobile-sidebar-backdrop -->

		<!-- BEGIN #content -->
		<div id="content" class="app-content">
{#        <div class="container">#}
        {% block content_head %}
{#			<ul class="breadcrumb">#}
{#				<li class="breadcrumb-item"><a href="#">BREADCRUMB</a></li>#}
{#				<li class="breadcrumb-item active">HOME PAGE</li>#}
{#			</ul>#}
{#			#}
{#			<h1 class="page-header">#}
{#				Starter Page <small>page header description goes here...</small>#}
{#			</h1>#}
		{% endblock content_head %}
        {% block content_body %}
			<p>
				Start build your page here
			</p>
        {% endblock content_body %}
{#        </div>#}
		</div>
		<!-- END #content -->

		<!-- BEGIN btn-scroll-top -->
		<a href="#" data-toggle="scroll-to-top" class="btn-scroll-top fade"><i class="fa fa-arrow-up"></i></a>
		<!-- END btn-scroll-top -->
	</div>
	<!-- END #app -->
	{% block js %}
	<!-- ================== BEGIN core-js ================== -->
	<script src={% static "assets/js/vendor.min.js" %}></script>
	<script src={% static "assets/js/app.min.js" %}></script>


	<!-- ================== END core-js ================== -->
	{% endblock js %}
	
</body>
</html>