bizanalytic/logiflex/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "logiflex"


newsletter_patterns = [
    path("create/", views.NewsletterCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.NewsletterEditView.as_view(), name="edit"),
    path("list/", views.NewsletterListView.as_view(), name="list"),
    path("subscrib/", views.NewsletterSubscriptionCreateView.as_view(), name="subscrib"),
    path("editsubscrib/<int:pk>/", views.NewsletterSubscriptionEditView.as_view(), name="editsubscrib"),
    path("subscribtionlist/", views.NewsletterSubscriptionListView.as_view(), name="subscribtionlist"),
]

report_patterns = [
    path("create/", views.SampleReportCreateView.as_view(), name="create"),

]

stripe_patterns = [
    path('', views.Payment_PageView.as_view(), name='payment_page'),
    path('create-checkout-session/', views.create_checkout_session, name='create_checkout_session'),
    path('stripe_webhook/', views.WebhookView.as_view(), name='stripe_webhook'),
    path('success/', views.Payment_SuccessView.as_view(), name='success'),
    path('cancel/', views.Payment_FailView.as_view(), name='cancel'),
]

urlpatterns = [

    path("", views.IndexView.as_view(), name="index"),
    path("book-call/", views.RequestCallView.as_view(), name="book-call"),
    path("bookcall/", views.BookACallView.as_view(), name="bookcall"),
    path(
        "newsletters/",
        include((newsletter_patterns, "bizanalytic.logiflex"), namespace="newsletters"),
    ),
    path(
        "reports/",
        include((report_patterns, "bizanalytic.logiflex"), namespace="reports"),
    ),
    path(
        "securepay/",
        include((stripe_patterns, "bizanalytic.logiflex"), namespace="securepay"),
    ),

]

bizanalytic/profiles/urls.py
from django.urls import path, include, re_path
from . import views

app_name = "profiles"

enterprise_patterns = [
    path("create/", views.EnterpriseCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", views.EnterpriseEditView.as_view(), name="edit"),
]


urlpatterns = [
    path("language/<int:pk>/", views.LanguageUpdateView.as_view(), name="language"),
    path("userinfo/<int:pk>/", views.ProfilesUpdateView.as_view(), name="userinfo"),
    path("activate/<int:pk>/", views.ProfileActivateView.as_view(), name="activate"),
    path("", views.ProfileDetailView.as_view(), name="profile"),
    path("edit/", views.ProfileView.as_view(), name="editprofile"),
    path("dispatch-login/", views.DispatchLoginView.as_view(), name="dispatch_login"),
    path("member/", views.RegularUpdateView.as_view(), name="regular"),
    path("admin/", views.AdminUpdateView.as_view(), name="admin"),
    # path("<int:pk>/add-review", views.ReviewCreateView.as_view(), name="review_create"),
    path("<int:pk>/contact-request/", views.ContactRequestView.as_view(), name="contact_request"),
    path("detail/<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("403/", views.ForbiddenView.as_view(), name="403"),
    path("conditions/", views.ConditionsView.as_view(), name="conditions"),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    # path("Freecourses/", views.FreecoursesView.as_view(), name="freecourses"),
    # path("uploadusers/", views.user_upload, name="userupload"),
    # path("uploadposts/", views.posts_upload, name="uploadposts"),
    # path("createusers/", views.UsersCreate.as_view(), name="createusers"),
    # url('^createnewusers$', views.NewUserCreateView.as_view(), name="createnewusers"),
    # path("tenants/", include((tenants_patterns, "syndicma.profiles"), namespace="tenants")),
    path(
        "enterprise/",
        include((enterprise_patterns, "bizanalytic.profiles"), namespace="enterprise"),
    ),
    # path(
    #     "activeyear/",
    #     include((activeyear_patterns, "syndicma.profiles"), namespace="activeyears"),
    # ),
]

bizanalytic/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog
# from api.verify.views import FileUpdateView, DocumentScanView, PictureVerifyView, FileUpdatetestView, \
#     DocumentVerifiedView, HeadshotVerifiedView

# from coelinks.profiles.views import ProfileView
# from rest_framework.routers import DefaultRouter
# from api.verify.views import FileUpdateView, DocumentScanView
# from api.chatbot.views import ChatGenerateView
#
# router = DefaultRouter()
#
# router.register(r"verify/", FileUpdateView, basename="verify")
# router.register(r"chat/", ChatGenerateView, basename="chat")

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path("logiflex/", include("bizanalytic.logiflex.urls", namespace="logiflex")),
    path("", RedirectView.as_view(pattern_name="logiflex:index")),
    path("accounts/", include("allauth.urls")),
    # path("accounts/profile/", ProfileView.as_view()),
    # path("apis/chat/", include("api.chat.urls", namespace="chat")),
    path("profiles/", include("bizanalytic.profiles.urls", namespace="profiles")),
    # path("coeanalytics/", include("coelinks.coeanalytics.urls", namespace="coeanalytics")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("i18n/", include("django.conf.urls.i18n")),




    # path('api/verify/', FileUpdateView.as_view(), name='verify'),
    # path('api/testverify/', FileUpdatetestView.as_view(), name='testverify'),
    # path('api/scan/', DocumentScanView.as_view(), name='scan'),
    # path('api/endverify/', DocumentVerifiedView.as_view(), name='endverify'),
    # path('api/headshotverified/', HeadshotVerifiedView.as_view(), name='headshotverified'),
    # path('api/checkimage/', PictureVerifyView.as_view(), name='checkimage'),
    # path('api/chat/', include('api.chatbot.urls', namespace='chat')),
    # path("api/ocr/", include('api.ocrserver.urls', namespace='ocr')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bizanalytic/logiflex/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.translation import gettext_lazy as _
from bizanalytic.profiles.formatChecker import ContentTypeRestrictedFileField
import os

from bizanalytic.profiles.models import User
# Create your models here.


def datafiles_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'data_files/route_files/company_id_{0}/{1}'.format(instance.client.id, filename)

def reportfiles_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'data_files/report_files/company_id_{0}/{1}'.format(instance.client.id, filename)


class NewsLetter_logiflex(models.Model):
    title = models.CharField(max_length=250, null=True, blank=True)
    body = RichTextField()
    date_created = models.DateTimeField(auto_now=True)
    dispatched = models.BooleanField(default=False)

    class Meta:
        verbose_name = "NewsLetter_logiflex"
        verbose_name_plural = "NewsLetters_logiflex"
        permissions = (("manage_logiflex_newsletters", "Manage Logiflex NewsLetters"),)

    def __str__(self):
        return str(self.title)


class NewsLetter_logiflex_subscription(models.Model):
    areatype = (
        ('lo', _("LogiFlex")),
        ('ki', _("KPI-Insights")),
    )
    email = models.CharField(max_length=150)
    company = models.CharField(max_length=150, null=True, blank=True)
    area = models.CharField(max_length=2, choices=areatype, null=True, blank=True)
    date_added = models.DateField(auto_now=True)
    removed = models.BooleanField(default=False)

    class Meta:
        verbose_name = "NewsLetter_logiflex_subscription"
        verbose_name_plural = "NewsLetter_logiflex_subscriptions"
        permissions = (("manage_logiflex_newsletters_subscription", "Manage Logiflex NewsLetters Subscription"),)

    def __str__(self):
        return str(self.email)


class LogiFlexClient(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    company = models.CharField(max_length=150)
    email = models.CharField(max_length=150)
    phone = models.CharField(max_length=20)
    contact_name = models.CharField(max_length=100, null=True, blank=True)
    date_added = models.DateField(auto_now=True)

    class Meta:
        verbose_name = "LogiFlexClient"
        verbose_name_plural = "LogiFlexClients"
        permissions = (("manage_logiflexclient", "Manage LogiFlex Clients"),)

    def __str__(self):
        return str(self.company)


class LogiflexReport(models.Model):
    client = models.ForeignKey(LogiFlexClient, on_delete=models.CASCADE)
    routefile = ContentTypeRestrictedFileField(upload_to=datafiles_directory_path,
                                               content_types=['application/vnd.ms-excel', 'text/csv',
                                                              'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', ],
                                               max_upload_size=20971520, blank=True, null=True)
    report = models.FileField(upload_to=reportfiles_directory_path, null=True, blank=True)
    download_code = models.CharField(max_length=6)
    date_created = models.DateField(auto_now=True)

    class Meta:
        verbose_name = "LogiFlexReport"
        verbose_name_plural = "LogiFlexReports"
        permissions = (("manage_Logiflexreport", "Manage LogiFlex Reports"),)

    def routefilename(self):
        return os.path.basename(self.routefile.name)

    def reportilename(self):
        return os.path.basename(self.report.name)

    def __str__(self):
        return str(self.client.id)


class RequestedCall(models.Model):
    client = models.ForeignKey(LogiFlexClient, on_delete=models.CASCADE)
    date_requested = models.DateTimeField(auto_now=True)
    called = models.BooleanField(default=False)
    date_called = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name = "RequestedCall"
        verbose_name_plural = "RequestedCalls"
        permissions = (("manage_requestedcall", "Manage RequestedCall"),)

bizanalytic/logiflex/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from . import models


class NewsLetter_logiflexForm(forms.ModelForm):
    class Meta:
        model = models.NewsLetter_logiflex
        fields = ["title", "body"]
        labels = {
            "title": _("Title"),
            "body": _("Body")
        }


class NewsLetter_logiflex_subscriptionForm(forms.ModelForm):
    class Meta:
        model = models.NewsLetter_logiflex_subscription
        fields = ["email", "company", "area"]
        labels = {
            "email": _("Email"),
            "company": _("Company Name"),
            "area": _("Area")
        }

bizanalytic/profiles/views.py
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import (
    UpdateView,
    RedirectView,
    CreateView,
    View,
    TemplateView,
    DetailView,
    ListView,
    DeleteView,
)
# from django.utils import timezone
from django.utils.translation import gettext_lazy as _
# from django.shortcuts import get_object_or_404
# from django.contrib.auth.models import Permission, Group
from django.contrib.auth import get_user_model
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.auth.hashers import make_password
# from django.contrib import messages
# from django.core.exceptions import ValidationError
# from django.utils.text import slugify
from . import forms, models
from .mixins import (MemberRequiredMixin, AdminRequiredMixin, AdminAllowedMixing, JsonFormMixin)
# from datetime import datetime, date, timedelta
User = get_user_model()


class ProfileActivateView(AdminRequiredMixin, UpdateView):
    model = User
    fields = ["is_active"]
    template_name = "profiles/activate_form.html"
    formset_class = None
    success_url = reverse_lazy("profiles:profile")

    # def form_valid(self, form):
    #     pk = self.kwargs.get("pk")
    #     if self.request.user.pk==pk:
    #         form.save()
    #     else:
    #         raise ValidationError(_("You don't have authorization to make that change"))
    #     return super().form_valid(form)

    def get_context_data(self, **kwargs):

        kwargs["title"] = _("Deactivate your Account")

        return super().get_context_data(**kwargs)


class ProfilesUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["username", "first_name", "last_name", "picture"]
    template_name = "profiles/user_form.html"
    formset_class = None
    success_url = reverse_lazy("profiles:profile")

    # def form_valid(self, form):
    #     pk = self.kwargs.get("pk")
    #     if self.request.user.pk==pk:
    #         form.save()
    #     else:
    #         raise ValidationError(_("You don't have authorization to make that change"))
    #     return super().form_valid(form)
    def get_context_data(self, **kwargs):

        kwargs["title"] = _("Your Personal Info")

        return super().get_context_data(**kwargs)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["email"]
    formset_class = None

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["formset"] = self.formset_class(
                self.request.POST, self.request.FILES, instance=self.object
            )
        else:
            context["formset"] = self.formset_class(instance=self.object)

        kwargs["title"] = _("Your Profile")

        return context

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        formset = context["formset"]

        if formset.is_valid():
            response = super().form_valid(form)
            formset.instance = self.object
            formset.save()
            return response
        else:
            return super().form_invalid(form)


class LanguageUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = forms.LanguageForm
    template_name = "profiles/language_form.html"
    success_url = reverse_lazy("profiles:profile")

    def get_context_data(self, **kwargs):

        kwargs["title"] = _("Language")

        return super().get_context_data(**kwargs)


class AdminUpdateView(AdminRequiredMixin, ProfileUpdateView):
    template_name = "profiles/profile_form.html"
    success_url = reverse_lazy("profiles:profile")
    formset_class = forms.AdminFormSet

    def get_context_data(self, **kwargs):

        kwargs["title"] = _("Your Profile")

        return super().get_context_data(**kwargs)

    # def get_form_kwargs(self):
    #     kwargs = super(ParentUpdateView, self).get_form_kwargs()
    #     year = 1930
    #     YEARS = [year + i for i in range(70)]
    #     kwargs.update({"yearofbirth": self.request.user.professor})
    #     return kwargs

class RegularUpdateView(MemberRequiredMixin, ProfileUpdateView):
    template_name = "profiles/profile_form.html"
    success_url = reverse_lazy("profiles:profile")
    formset_class = forms.RegularFormSet

    def get_context_data(self, **kwargs):

        kwargs["title"] = _("Your Profile")

        return super().get_context_data(**kwargs)


class ProfileDetailView(LoginRequiredMixin, TemplateView):
    template_name = "profiles/profile.html"


class ProfileView(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        if hasattr(self.request.user, "admin"):
            return reverse_lazy("profiles:admin")
        elif hasattr(self.request.user, "member"):
            return reverse_lazy("profiles:member")

        return super().get_redirect_url(*args, **kwargs)


class DispatchLoginView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        if hasattr(self.request.user, "admin"):
            return reverse_lazy("logiflex:index")
        elif hasattr(self.request.user, "member"):
            return reverse_lazy("logiflex:index")
        else:
            return reverse_lazy("logiflex:index")

        return super().get_redirect_url(*args, **kwargs)


class ContactRequestView(SingleObjectMixin, View):
    model = models.User

    def post(self, *args, **kwargs):
        admin = self.get_object()
        admin.contacts_requests += 1
        admin.save()
        return HttpResponse()


class EnterpriseCreateView(LoginRequiredMixin, CreateView):
    model = models.Enterprise
    form_class = forms.EnterpriseForm
    template_name = "profiles/enterprise_edit.html"
    success_url = reverse_lazy("logiflex:index")


class EnterpriseEditView(LoginRequiredMixin, CreateView):
    model = models.Enterprise
    form_class = forms.EnterpriseForm
    template_name = "profiles/enterprise_edit.html"
    success_url = reverse_lazy("logiflex:index")


class UserDetailView(DetailView, SingleObjectMixin):
    model = models.User
    template_name = "profiles/user_detail.html"


class ForbiddenView(TemplateView):
    template_name = "../templates/403.html"


class ConditionsView(TemplateView):
    template_name = "../templates/conditions.html"


class PrivacyView(TemplateView):
    template_name = "../templates/privacy.html"

bizanalytic/templates/profiles/acayear_edit.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content_title %}
  <h2 class="h3">{% trans "Active Year" %}</h2>
{% endblock content_title %}
{% block css %}
    {{ block.super }}

{% endblock css %}


{% block content %}
     <div class="page-header">
				<div class="page-header-content header-elements-md-inline">
					<div class="page-title d-flex">
						<h4>
                            <button type="button" class="btn btn-outline bg-primary text-primary-800 btn-icon ml-2" onclick="goBack()">
                            <i class="icon-arrow-left52 mr-2" ></i></button>
                            {% trans "Active Year Menu" %}</h4>
						<a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
					</div>


				</div>
    </div>

    <div class="d-md-flex align-items-md-start justify-content-center">
        <div class="tab-content w-md-75">




                <div class="card">
                    <div class="card-header header-elements-inline">
                       <h6 class="card-title">{% trans "Edit Academic Year" %}</h6>


								<div class="header-elements">
									<div class="list-icons">
				                		<a class="list-icons-item" data-action="collapse"></a>
				                		<a class="list-icons-item" data-action="reload"></a>
{#				                		<a class="list-icons-item" data-action="remove"></a>#}
				                	</div>
			                	</div>




                    </div>
                    <div class="card-body">
                        <form action="" class="p-1" method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            {{ form|crispy }}
                            <div class="form-group">
                              <input type="submit" value='{% trans "Submit" %}' class="btn btn-primary py-3 px-5 mt-3">
                            </div>
                      </form>


                    </div>
                    <div class="card-footer">


                    </div>
                </div>

            </div>

        </div>



{% endblock content %}




{% block project_js %}
  {{ block.super }}
  <script src={% static "vendor/jquery.formset.jss" %}></script>
  <script src={% static "jss/center_edit.jss" %}></script>

    <script>
function goBack() {
  window.history.back();
}
</script>
{% endblock project_js %}

bizanalytic/templates/profiles/profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
    <meta charset="utf-8">
  <h1 class="mb-0 pb-0 display-4" id="title">{% trans "Profile Overview" %}</h1>
    <nav class="breadcrumb-container d-inline-block" aria-label="breadcrumb">
        <ul class="breadcrumb pt-0">
            <li class="breadcrumb-item"><a href="{% url 'idmeapi:sdashboard' %}">{% trans "Home" %}</a></li>
            <li class="breadcrumb-item"><a href="">{% trans "Profile" %}</a></li>

        </ul>
    </nav>

<link href={% static "assets/css/vendor.min.css" %} rel="stylesheet">
<link href={% static "assets/css/app.min.css" %} rel="stylesheet">

{% block content_head %}
<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">{% trans "Home" %}</a></li>
    <li class="breadcrumb-item active">{% trans "Profile" %}</li>
</ul>

<h1 class="page-header">
    {% trans "Profile Management" %}
</h1>
{% endblock content_head %}

{% block content_body %}

<div class="row gx-4">
    <div class="col-lg-6">
        <!-- Biography Start -->

        <div class="card mb-5">

            <div class="card-body">
                <div class="card">
                    <div class="card-body pt-4 pb-4 text-center">
                        {% if user.picture %}
                        <img class="img-fluid" src="{{ user.picture.url }}" style="border-radius: 50%; max-width: 200px; height: 200px" alt="">
                        {% else %}
                        <img class="img-fluid" style="border-radius: 50%;" src="{% static "pictures/user_placeholder.png" %}" width="170" height="170" alt="">
                        {% endif %}
                    </div>
                    <div class="card-footer text-center">
                        <div class="h5 mb-0">{{ user.first_name }} {{ user.last_name }}</div>
                        <div class="text-muted">
                            <i class="fas fa-md fa-fw me-2 fa-map-marker-alt"></i>
                            <span class="align-middle">{{ user.profile.city }}, {{ user.profile.country }}</span>
                        </div>
                    </div>
                    <div class="card-arrow">
                        <div class="card-arrow-top-left"></div>
                        <div class="card-arrow-top-right"></div>
                        <div class="card-arrow-bottom-left"></div>
                        <div class="card-arrow-bottom-right"></div>
                    </div>
                </div>




                <div class="card text-center">
                    <div class="card-body pt-4 pb-4">
                        <a class="nav-link active px-0 border-bottom border-separator-light"  href="{% url 'profiles:userinfo' user.pk %}" >
                            <i data-cs-icon="user" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "User Information" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light"  href="{% url 'profiles:editprofile' %}" >
                            <i data-cs-icon="settings-1" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Edit Profile" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light"  href="{% url 'account_change_password' %}" >
                            <i data-cs-icon="lock-off" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Manage Password"  %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light" href="{% url "account_email" %}" >
                        <i data-cs-icon="email" class="me-2" data-cs-size="17"></i>
                        <span class="align-middle">{% trans "Manage Emails" %}</span>
                        </a>
                        <a class="nav-link active px-0 border-bottom border-separator-light"  href="{% url 'mfa_index' %}" >
                            <i data-cs-icon="user" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Enable 2FA with Autheticator App" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light" href="{% url 'profiles:language' user.pk %}" >
                            <i data-cs-icon="web" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Prefered Language" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light" href="{% url 'profiles:activate' user.pk %}" >
                            <i data-cs-icon="eye-off" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Deactivate" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light" href="{% url 'profiles:services:list' %}" >
                            <i data-cs-icon="eye-off" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Services" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light" href="{% url 'profiles:payments:list' %}" >
                            <i data-cs-icon="eye-off" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Payments" %}</span>
                        </a>
                        <a class="nav-link px-0 border-bottom border-separator-light" href="{% url 'profiles:logout' %}" >
                            <i data-cs-icon="logout" class="me-2" data-cs-size="17"></i>
                            <span class="align-middle">{% trans "Logout" %}</span>
                        </a>


                    </div>
                    <div class="card-arrow">
                        <div class="card-arrow-top-left"></div>
                        <div class="card-arrow-top-right"></div>
                        <div class="card-arrow-bottom-left"></div>
                        <div class="card-arrow-bottom-right"></div>
                    </div>
                </div>
            </div>
            <div class="card-arrow">
                        <div class="card-arrow-top-left"></div>
                        <div class="card-arrow-top-right"></div>
                        <div class="card-arrow-bottom-left"></div>
                        <div class="card-arrow-bottom-right"></div>
                    </div>
        </div>
        <div class="card-arrow">
            <div class="card-arrow-top-left"></div>
            <div class="card-arrow-top-right"></div>
            <div class="card-arrow-bottom-left"></div>
            <div class="card-arrow-bottom-right"></div>
        </div>
    </div>
    <!-- Biography End -->
</div>




{% endblock content_body %}



{% block js %}
  {{ block.super }}

<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock js %}

bizanalytic/templates/profiles/upload_users.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content_title %}
  <h2 class="h3">{% trans "Profile" %}</h2>
{% endblock content_title %}

{% block main %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
      <p>Please select the format of your file</p>
      <select name="file-format" class="form-control my-3">
          <option selected>Choose format...</option>
          <option>CSV</option>
          <option>XLSX</option>
           <option>XLS</option>
        </select>
      <select name="user_type" class="form-control my-3">
          <option selected>Choose you user...</option>
           <option>parent</option>
           <option>student</option>
        </select>
    <button type="submit">Upload</button>
  </form>
{% endblock main %}

{% block project_js %}
  {{ block.super }}

<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock project_js %}